blueprint:
  name: "Obwody Krytyczne (Smart Recovery)"
  description: >
    System ochrony zasilania z INTELIGENTNYM POWROTEM.
    
    1. AWARIA SIECI (< Limit V) -> Wyłącza GRUPĘ 1 (Największe odbiorniki).
    2. SŁABA BATERIA (< Limit 1) -> Wyłącza GRUPĘ 2 (Ostrzegawcze).
    3. PUSTA BATERIA (< Limit 2) -> Wyłącza GRUPĘ 3 (Reszta domu).
    
    POWRÓT ZASILANIA (Sekwencja Startu):
    Najpierw GRUPA 3 (Najważniejsze) -> potem GRUPA 2 -> na końcu GRUPA 1 (Duże obciążenia).
  domain: automation
  source_url: https://github.com/zxvxv/obwody/blob/main/blueprint.yaml
  input:
    # --- CZUJNIKI ---
    grid_voltage_l1:
      name: "Sensor Napięcia L1"
      default: sensor.deye_inverter_grid_l1_voltage
      selector:
        entity:
          domain: sensor
          device_class: voltage
    grid_voltage_l2:
      name: "Sensor Napięcia L2"
      default: sensor.deye_inverter_grid_l2_voltage
      selector:
        entity:
          domain: sensor
          device_class: voltage
    grid_voltage_l3:
      name: "Sensor Napięcia L3"
      default: sensor.deye_inverter_grid_l3_voltage
      selector:
        entity:
          domain: sensor
          device_class: voltage
    battery_soc:
      name: "Sensor Baterii (SOC)"
      default: sensor.deye_inverter_battery_bms_soc
      selector:
        entity:
          domain: sensor

    # --- PROGI ---
    voltage_limit:
      name: "Próg Napięcia - AWARIA (V)"
      default: 190
      selector:
        number:
          min: 150
          max: 230
          unit_of_measurement: V
          mode: box
    
    soc_limit_1:
      name: "Próg Baterii - OSTRZEGAWCZY (%)"
      default: 80
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

    soc_limit_2:
      name: "Próg Baterii - KRYTYCZNY (%)"
      default: 20
      selector:
        number:
          min: 0
          max: 100
          unit_of_measurement: "%"
          mode: slider

    # --- OBWODY ---
    targets_group_1:
      name: "GRUPA 1: Awaria Sieci / Hard Stop"
      description: "Te urządzenia gasną PIERWSZE przy awarii, a wstają OSTATNIE (Duże AGD)."
      selector:
        target:
          entity:
            domain: switch

    targets_group_2:
      name: "GRUPA 2: Słaba Bateria"
      description: "Te urządzenia gasną przy pierwszym progu (np. 80%)."
      selector:
        target:
          entity:
            domain: switch

    targets_group_3:
      name: "GRUPA 3: Pusta Bateria / Full Shutdown"
      description: "Te urządzenia gasną OSTATNIE, a wstają PIERWSZE (Kluczowe systemy)."
      selector:
        target:
          entity:
            domain: switch

    # --- POWRÓT ---
    voltage_recovery:
      name: "Próg Napięcia - POWRÓT (V)"
      default: 215
      selector:
        number:
          min: 190
          max: 250
          unit_of_measurement: V
          mode: box

trigger:
  - platform: numeric_state
    entity_id: !input grid_voltage_l1
    below: !input voltage_limit
    id: grid_fail
  - platform: numeric_state
    entity_id: !input grid_voltage_l2
    below: !input voltage_limit
    id: grid_fail
  - platform: numeric_state
    entity_id: !input grid_voltage_l3
    below: !input voltage_limit
    id: grid_fail
  - platform: numeric_state
    entity_id: !input battery_soc
    below: !input soc_limit_1
    id: soc_1
  - platform: numeric_state
    entity_id: !input battery_soc
    below: !input soc_limit_2
    id: soc_2
  - platform: numeric_state
    entity_id: !input grid_voltage_l1
    above: !input voltage_recovery
    for: "00:00:30"
    id: grid_ok
  - platform: numeric_state
    entity_id: !input grid_voltage_l2
    above: !input voltage_recovery
    for: "00:00:30"
    id: grid_ok
  - platform: numeric_state
    entity_id: !input grid_voltage_l3
    above: !input voltage_recovery
    for: "00:00:30"
    id: grid_ok

action:
  - choose:
      - conditions:
          - condition: trigger
            id: grid_fail
        sequence:
          - service: persistent_notification.create
            data:
              title: "⚡ AWARIA"
              message: "Napięcie spadło! Wyłączam Grupę 1 (Duże AGD)."
          - service: switch.turn_off
            target: !input targets_group_1
      - conditions:
          - condition: trigger
            id: soc_1
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: !input grid_voltage_l1
                below: !input voltage_limit
              - condition: numeric_state
                entity_id: !input grid_voltage_l2
                below: !input voltage_limit
              - condition: numeric_state
                entity_id: !input grid_voltage_l3
                below: !input voltage_limit
        sequence:
          - service: persistent_notification.create
            data:
              title: "🔋 BATERIA SŁABA"
              message: "Wyłączam Grupę 2."
          - service: switch.turn_off
            target: !input targets_group_2
      - conditions:
          - condition: trigger
            id: soc_2
          - condition: or
            conditions:
              - condition: numeric_state
                entity_id: !input grid_voltage_l1
                below: !input voltage_limit
              - condition: numeric_state
                entity_id: !input grid_voltage_l2
                below: !input voltage_limit
              - condition: numeric_state
                entity_id: !input grid_voltage_l3
                below: !input voltage_limit
        sequence:
          - service: persistent_notification.create
            data:
              title: "🪫 BATERIA KRYTYCZNA"
              message: "Wyłączam Grupę 3 (Total Shutdown)."
          - service: switch.turn_off
            target: !input targets_group_3
      - conditions:
          - condition: trigger
            id: grid_ok
          - condition: numeric_state
            entity_id: !input grid_voltage_l1
            above: !input voltage_recovery
          - condition: numeric_state
            entity_id: !input grid_voltage_l2
            above: !input voltage_recovery
          - condition: numeric_state
            entity_id: !input grid_voltage_l3
            above: !input voltage_recovery
        sequence:
          - service: persistent_notification.create
            data:
              title: "✅ POWRÓT ZASILANIA"
              message: "Sieć stabilna >30s. Przywracam zasilanie kaskadowo (od najważniejszych)."
          # 1. Najpierw najważniejsze (Grupa 3)
          - delay: "00:00:05"
          - service: switch.turn_on
            target: !input targets_group_3
          # 2. Potem średnie (Grupa 2)
          - delay: "00:00:05"
          - service: switch.turn_on
            target: !input targets_group_2
          # 3. Na końcu obciążenia (Grupa 1)
          - delay: "00:00:05"
          - service: switch.turn_on
            target: !input targets_group_1
mode: restart
